### PR TITLE
fetchCheriSDK.groovy: Build demo-2024-06 with custom Morello LLVM

### PR DESCRIPTION
**Pull request by dpgao**
This demo branch needs to be built with a Morello LLVM branch that emits function signatures and wraps function pointers in trampolines.

### CODE REVIEW

**Comment by jrtc27** [comment]
You can't just point it at an arbitrary branch Jenkins doesn't know about

**Comment by jrtc27** [comment]
What's the point of making a pull request if you're going to merge it after I tell you it won't work?

**Comment by dpgao** [comment]
@jrtc27 Sorry about that. I hit the merge button before the page refreshed to show your comment.

I was going through the list of things you posted on Slack to add a demo branch. I think I've done all four items. Which branch are you referring to? The morello-llvm branch or the CheriBSD branch?

**Comment by jrtc27** [comment]
Morello LLVM. They have to actually be built by Jenkins. My post to Slack was on the assumption that people would want the demo branch to be using morello/dev rather than morello/master, not some other arbitrary branch.

**Comment by jrtc27** [comment]
Also, merging before you saw the comment is even worse. Why would you put a PR up, request a review and then merge 10 minutes later without getting any feedback?

**Comment by dpgao** [comment]
Apologies again. I don't know why I did that.

How do I make Jenkins build the custom Morello LLVM branch?

**Comment by jrtc27** [comment]
Add it to the list of branches to discover in Jenkins:

image

**Comment by jrtc27** [comment]
Though you'll also need to tell it to archive the results otherwise it'll throw away the binaries once built and tested, which is configured by archiveBranches in jobs/morello-llvm.groovy in this repo.

**Pull request merged**
